import { tool } from 'ai'

import { webSchema } from '@/lib/schema/web'

/**
 * A tool that creates a simple, client-only web project (HTML/CSS/JS).
 * The result includes a basic file tree the UI can render and edit live.
 */
export function createWebTool(fullModel: string) {
  return tool({
    description:
      'Create a website project with HTML, CSS, and JavaScript files. Use this tool when the user asks to create, build, or make a website, landing page, or web demo. Returns editable files with live preview.',
    parameters: webSchema,
    execute: async ({ title, description, include_js = true, template = 'blank' }) => {
      const projectTitle = title || 'My Website'
      const projectDescription = description || 'A simple site generated by the assistant.'

      const css = `/* styles.css */\n:root{\n  --bg:#0b1020;\n  --card:#0f172a;\n  --text:#e2e8f0;\n  --accent:#60a5fa;\n}\n*{box-sizing:border-box}body{margin:0;font-family:system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, Noto Sans, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol;background:var(--bg);color:var(--text);}\n.container{max-width:960px;margin:0 auto;padding:2rem;}\n.header{display:flex;align-items:center;justify-content:space-between;margin-bottom:1rem;}\n.brand{font-weight:700;letter-spacing:.3px}nav a{color:var(--text);opacity:.85;text-decoration:none;margin-left:1rem;font-size:.9rem}nav a:hover{opacity:1}main{background:var(--card);border:1px solid #1f2937;border-radius:12px;padding:2rem;}h1{font-size:1.6rem;margin:0 0 1rem}p{margin:0 0 1rem;opacity:.9}button{background:var(--accent);border:0;color:#0b1020;padding:.6rem .9rem;border-radius:999px;font-weight:600;cursor:pointer}button:hover{filter:brightness(1.1)}\nfooter{opacity:.7;margin-top:1rem;text-align:center;font-size:.8rem}\n`

      const js = `// script.js\nconsole.log('Hello from script.js')\nconst btn=document.getElementById('action-btn');\nif(btn){btn.addEventListener('click',()=>{alert('Action clicked!')})}\n`

      const baseBody = template === 'landing'
        ? `<main>\n  <h1>${projectTitle}</h1>\n  <p>${projectDescription}</p>\n  <button id="action-btn">Get Started</button>\n</main>`
        : template === 'portfolio'
          ? `<main>\n  <h1>${projectTitle}</h1>\n  <p>${projectDescription}</p>\n  <section class="grid" style="display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:1rem">\n    <article style="background:#0b1229;border:1px solid #253056;border-radius:12px;padding:1rem">Project A</article>\n    <article style="background:#0b1229;border:1px solid #253056;border-radius:12px;padding:1rem">Project B</article>\n    <article style="background:#0b1229;border:1px solid #253056;border-radius:12px;padding:1rem">Project C</article>\n  </section>\n</main>`
          : `<main>\n  <h1>${projectTitle}</h1>\n  <p>${projectDescription}</p>\n</main>`

      const html = `<!doctype html>\n<html lang="en">\n<head>\n  <meta charset="utf-8"/>\n  <meta name="viewport" content="width=device-width, initial-scale=1"/>\n  <title>${projectTitle}</title>\n  <link rel="stylesheet" href="styles.css"/>\n</head>\n<body>\n  <div class="container">\n    <header class="header">\n      <div class="brand">${projectTitle}</div>\n      <nav>\n        <a href="#">Home</a>\n        <a href="#">About</a>\n        <a href="#">Contact</a>\n      </nav>\n    </header>\n    ${baseBody}\n    <footer>Built with Modalis</footer>\n  </div>\n  ${include_js ? '<script src="script.js"></script>' : ''}\n</body>\n</html>`

      const files: Array<{ path: string; language: 'html'|'css'|'js'; content: string }> = [
        { path: 'index.html', language: 'html', content: html },
        { path: 'styles.css', language: 'css', content: css }
      ]
      if (include_js) files.push({ path: 'script.js', language: 'js', content: js })

      return {
        title: projectTitle,
        description: projectDescription,
        template,
        files
      }
    }
  })
}

// Default for compatibility
export const webTool = createWebTool('openai:gpt-4o-mini')
